/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LiNav {
        "icon": string;
        "link": string;
        "text": string;
    }
    interface MyBtn {
        "text": string;
    }
    interface MyCard {
        "img": string;
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyLink {
        "link": string;
        "text": string;
    }
    interface TextBox {
        "text": string;
    }
}
declare global {
    interface HTMLLiNavElement extends Components.LiNav, HTMLStencilElement {
    }
    var HTMLLiNavElement: {
        prototype: HTMLLiNavElement;
        new (): HTMLLiNavElement;
    };
    interface HTMLMyBtnElement extends Components.MyBtn, HTMLStencilElement {
    }
    var HTMLMyBtnElement: {
        prototype: HTMLMyBtnElement;
        new (): HTMLMyBtnElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyLinkElement extends Components.MyLink, HTMLStencilElement {
    }
    var HTMLMyLinkElement: {
        prototype: HTMLMyLinkElement;
        new (): HTMLMyLinkElement;
    };
    interface HTMLTextBoxElement extends Components.TextBox, HTMLStencilElement {
    }
    var HTMLTextBoxElement: {
        prototype: HTMLTextBoxElement;
        new (): HTMLTextBoxElement;
    };
    interface HTMLElementTagNameMap {
        "li-nav": HTMLLiNavElement;
        "my-btn": HTMLMyBtnElement;
        "my-card": HTMLMyCardElement;
        "my-component": HTMLMyComponentElement;
        "my-link": HTMLMyLinkElement;
        "text-box": HTMLTextBoxElement;
    }
}
declare namespace LocalJSX {
    interface LiNav {
        "icon"?: string;
        "link"?: string;
        "text"?: string;
    }
    interface MyBtn {
        "text"?: string;
    }
    interface MyCard {
        "img"?: string;
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyLink {
        "link"?: string;
        "text"?: string;
    }
    interface TextBox {
        "text"?: string;
    }
    interface IntrinsicElements {
        "li-nav": LiNav;
        "my-btn": MyBtn;
        "my-card": MyCard;
        "my-component": MyComponent;
        "my-link": MyLink;
        "text-box": TextBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "li-nav": LocalJSX.LiNav & JSXBase.HTMLAttributes<HTMLLiNavElement>;
            "my-btn": LocalJSX.MyBtn & JSXBase.HTMLAttributes<HTMLMyBtnElement>;
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-link": LocalJSX.MyLink & JSXBase.HTMLAttributes<HTMLMyLinkElement>;
            "text-box": LocalJSX.TextBox & JSXBase.HTMLAttributes<HTMLTextBoxElement>;
        }
    }
}
